version: "3.7"
services:
  gbook-doc:
    image: q9090960bnb3/gbook
    ports:
      - "4000:4000"
    tty: true
    volumes:
      - "./:/doc"
    working_dir: /doc
    command: bash -c "gbook install  && gbook serve"
